server:
  port: 8080
spring:
  application:
    name: SpringBootDemo_Cs0_Backeng
  datasource:
    url: jdbc:mysql:///demo_iti
    username: root
    password: Inaba
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    filter:
      order: -100
    jwt:
      key: ajiskyuxhjl
      expire: 7
  web:
    cors:
      origin: http://localhost:3000, sad
      header: Authorization, Content-Type
      method: GET, HEAD, POST, PUT, DELETE, OPTIONS, TRACE, PATCH