server:
  port: 8080
spring:
  application:
    name: SpringBootDemo_Cs0_Backeng
  datasource:
    url: jdbc:mysql:///demo_iti
    username: root
    password: Inaba
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: 123
      roles:
        - admin
        - user
    jwt:
      key: ajiskyuxhjl
      expire: 7